title: The CICIDS Analysis Project

project:
  repourl: https://github.com/r-dube/CICIDS
  imgurl: https://github.com/r-dube/CICIDS/docs/_images

description: > 
  Analyzing the University of New Brunswick CICIDS2017 dataset

show_excerpts: true # set to true to show excerpts on the homepage

theme: minima
