title: The IDS Analysis Project

project:
  repourl: https://github.com/r-dube/CICIDS

description: Analyzing the CICIDS2017 dataset

show_excerpts: true 

github_username: r-dube
rss: rss

theme: minima

plugins:
 - jekyll-feed
