title: The IDS Analysis Project

description: Data Science in Information Security

show_excerpts: true 

# For the footer of blog pages
github_username: r-dube
rss: rss

# for rss
url: https://r-dube.github.io

# For comments on posts
disqus:
    shortname: cicids

# Github pages Jekyll theme
theme: minima

# For the RSS button and feed.xml
plugins:
 - jekyll-feed
